### ISSUE TITLE
Alternative implementation of the Home Connect integration

### ISSUE THREAD

**Issue by ekutner** [DavidMStraub/homeconnect#15]
Hello, 
This is an unusual issue because it asks for a review and consideration of an alternative implementation for the Home Connect integration. This project started out as a personal learning exercise and ended up as a full featured implementation that takes a different approach to this one. In particular, almost all the entities are generic and get their data from the API, therefor they support all current and future appliances that may be offered by the service. It also allows for full control of the appliances, including selecting programs and options, starting a program, etc, and the implementation is fully async based and seems to solve some issues I encountered when working with the official Home Connect integration like stopping getting status updates after a while.
It would be great if you could take a look at https://github.com/ekutner/home-connect-hass (can be installed as a custom-repo with HACS as well if you'd like to give it a try). I don't think the world really needs two Home Connect integrations for Home Assistant so it would be great if we can figure out a way to integrate these projects.

Best,
Eran Kutner

**Comment by DavidMStraub** [comment]
Hi,

> I don't think the world really needs two Home Connect integrations for Home Assistant so it would be great if we can figure out a way to integrate these projects.

There is already a Core integration based on this library. If you want to replace it, you're free to do it via a pull request to Core, if it is approved.

I'm also willing to review & approve pull requests to this library if you have ideas to improve it, but I don't want to commit to more than that, especially not to working on a reimplementation myself.
