### ISSUE TITLE
Declare dependency on six

### ISSUE THREAD

**Issue by mweinelt** [DavidMStraub/homeconnect#18]
Used here:

https://github.com/DavidMStraub/homeconnect/blob/d16e3baeda2383f55617fe40003c92fcb192c03e/homeconnect/sseclient.py?rgh-link-date=2022-06-05T02%3A52%3A50Z#L10

**Comment by DavidMStraub** [comment]
Good point. I think it would be better to get rid of it, Python 2 is not supported.

**Comment by DavidMStraub** [comment]
Removed.
