### ISSUE TITLE
NameError: name 'auth_result' is not defined

### ISSUE THREAD

**Issue by Ev15** [DavidMStraub/homeconnect#9]
Hi, i get the following error when i try to run the program:

NameError: name 'auth_result' is not defined

What am i doing wrong ?

Thx Ed.

**Comment by DavidMStraub** [comment]
Hard to tell when you're not writing what exactly you're doing...

**Comment by Ev15** [comment]
I have made an account in Homeconnect. I don't really know what the redirect url should be. I think that is the problem ?
I am running your code on Windows btw. (python 3.8)

**Comment by DavidMStraub** [comment]
If you're just using this locally, it doesn't matter. Use `http://localhost` (but make sure to set it in the application settings at Home Connect). Your browser will redirect you to this address with some token append and it doesn't matter whether it exists - you just have to copy the address from the address bar in your browser.

**Comment by Ev15** [comment]
Do you mean this:  (this shows up after logging in into Homeconnect)
http://localhost/?code=eyJ4LXJlZyI6IkVVIiwieCHJUgHz8jJHGGnsnajwlbiI6ImQyODVkMzRmLTlkZGQtNGQ2Zi04dfkjdfkjh321kjh213kjh213jhMmQ5ZWUwNTIzNCIsImNsdHkiOiJwcml2YXRlIn0%3D&state=QXbhEpRlQXhLAd2vhbIXPzsFjh1IMV&grant_type=authorization_code

What should be the next step ?

**Comment by Ev15** [comment]
Got it working. Thank you.
